# Generated by Django 2.1.4 on 2019-03-24 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='video',
        ),
    ]
