# Generated by Django 2.1.4 on 2019-05-28 15:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0006_auto_20190422_2049'),
        ('brokers', '0002_auto_20181206_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adquisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.CharField(max_length=6)),
                ('end_date', models.CharField(max_length=6)),
                ('start_time', models.CharField(max_length=4)),
                ('end_time', models.CharField(max_length=4)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='brokers.Broker')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.CharField(max_length=6)),
                ('end_date', models.CharField(max_length=6)),
                ('start_time', models.CharField(max_length=4)),
                ('end_time', models.CharField(max_length=4)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='brokers.Broker')),
            ],
        ),
        migrations.CreateModel(
            name='ReContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.CharField(max_length=6)),
                ('end_date', models.CharField(max_length=6)),
                ('start_time', models.CharField(max_length=4)),
                ('end_time', models.CharField(max_length=4)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('recurrent_rule', models.CharField(max_length=10)),
                ('recurrent_count', models.CharField(max_length=10)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='brokers.Broker')),
            ],
        ),
        migrations.CreateModel(
            name='SalesEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.CharField(max_length=6)),
                ('end_date', models.CharField(max_length=6)),
                ('start_time', models.CharField(max_length=4)),
                ('end_time', models.CharField(max_length=4)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='brokers.Broker')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='listings.Listing')),
            ],
        ),
    ]
