# Generated by Django 2.1.4 on 2019-05-28 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('contact', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('caracteristics', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
