# Generated by Django 2.1.4 on 2019-05-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_api', '0003_auto_20190529_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adquisition',
            name='adquisition_id',
        ),
        migrations.RemoveField(
            model_name='news',
            name='news_id',
        ),
        migrations.RemoveField(
            model_name='recontact',
            name='recontact_id',
        ),
        migrations.RemoveField(
            model_name='salesevent',
            name='sales_event_id',
        ),
        migrations.AddField(
            model_name='adquisition',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recontact',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesevent',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
