# Generated by Django 2.1.4 on 2019-05-29 15:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_api', '0006_auto_20190529_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adquisition',
            name='adquisition_name',
        ),
        migrations.RemoveField(
            model_name='news',
            name='news_name',
        ),
        migrations.RemoveField(
            model_name='recontact',
            name='recontact_name',
        ),
        migrations.RemoveField(
            model_name='salesevent',
            name='sales_event_name',
        ),
        migrations.AddField(
            model_name='adquisition',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recontact',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesevent',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adquisition',
            name='address',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adquisition',
            name='description',
            field=models.TextField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='address',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recontact',
            name='address',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recontact',
            name='description',
            field=models.TextField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesevent',
            name='address',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesevent',
            name='description',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
