# Generated by Django 2.1.4 on 2019-05-31 10:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_api', '0008_auto_20190529_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adquisition',
            name='end',
        ),
        migrations.RemoveField(
            model_name='adquisition',
            name='start',
        ),
        migrations.RemoveField(
            model_name='news',
            name='end',
        ),
        migrations.RemoveField(
            model_name='news',
            name='start',
        ),
        migrations.RemoveField(
            model_name='recontact',
            name='end',
        ),
        migrations.RemoveField(
            model_name='recontact',
            name='start',
        ),
        migrations.RemoveField(
            model_name='salesevent',
            name='end',
        ),
        migrations.RemoveField(
            model_name='salesevent',
            name='start',
        ),
        migrations.AddField(
            model_name='adquisition',
            name='end_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adquisition',
            name='end_time',
            field=models.CharField(default=django.utils.timezone.now, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adquisition',
            name='start_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adquisition',
            name='start_time',
            field=models.CharField(default=django.utils.timezone.now, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='end_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='end_time',
            field=models.CharField(default=django.utils.timezone.now, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='start_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='start_time',
            field=models.CharField(default=django.utils.timezone.now, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recontact',
            name='end_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recontact',
            name='end_time',
            field=models.CharField(default=django.utils.timezone.now, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recontact',
            name='start_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recontact',
            name='start_time',
            field=models.CharField(default=django.utils.timezone.now, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesevent',
            name='end_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesevent',
            name='end_time',
            field=models.CharField(default=django.utils.timezone.now, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesevent',
            name='start_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesevent',
            name='start_time',
            field=models.CharField(default=django.utils.timezone.now, max_length=4),
            preserve_default=False,
        ),
    ]
