# Generated by Django 2.1.4 on 2019-06-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_api', '0009_auto_20190531_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesevent',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='salesevent',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='salesevent',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesevent',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
