# Generated by Django 2.1.4 on 2019-06-02 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_api', '0010_auto_20190602_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesevent',
            old_name='title',
            new_name='event_name',
        ),
    ]
