# Generated by Django 2.1.4 on 2019-06-02 08:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20190422_2049'),
        ('brokers', '0002_auto_20181206_2303'),
        ('calendar_api', '0013_auto_20190602_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='brokers.Broker')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='listings.Listing')),
            ],
        ),
        migrations.RemoveField(
            model_name='adquisition',
            name='broker',
        ),
        migrations.RemoveField(
            model_name='news',
            name='broker',
        ),
        migrations.RemoveField(
            model_name='recontact',
            name='broker',
        ),
        migrations.RemoveField(
            model_name='salesevent',
            name='broker',
        ),
        migrations.RemoveField(
            model_name='salesevent',
            name='listing',
        ),
        migrations.DeleteModel(
            name='Adquisition',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='ReContact',
        ),
        migrations.DeleteModel(
            name='SalesEvent',
        ),
    ]
