# Generated by Django 2.1.4 on 2019-06-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_api', '0014_auto_20190602_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
